# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tune Katerungroch
title: Senior System Administrator
email: contact@tunek.cloud
#website: https://www.linkedin.com/in/tunek/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  naamtune
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: tunek
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Tune Katerungroch, an IT professional based in Southern California, USA. Having accumulated over 14 years of professional IT experience, I have fostered excellence in the following specialties: open-source intelligence gathering, network engineering, and systems administration. I am currently working for Consolidated Precision Products as a security analyst.

  My passion in technologies took root in a humble beginning of building home computer with my father on the floor of the living room when I was a toddler. As I grew older, I self-taught myself technical skills and concepts through hand-on experience and contents made available on the Internet. In later life, my career growth took a leap forward as I begun to professionally collaborate with peers in the industry. 

  I enjoy tackling the challenges of managing projects, hardware logistics, and technical issues that spring up, as if they are minigames and puzzles. Networking issues. Infrastructure planning, and figuring out resources are just some of the shapes and forms where challenges arise. The problem-solving skills and thought process is always a reflection of one’s neuroplasticity and the quality of the mental framework. 

  Much of my IT career have been spent supporting infrastructure within the logistics and manufacturing industry, thus I have deep understanding of the business operations and how these businesses utilize IT to grow and expand.

  Outside of my professional life, I can be found in the outdoor settings rappelling down waterfalls with my teams, and scaling steep rocky desert mountains with my friends. If I’m not outside on weekend adventures as weekend warrior, I can also be found volunteering my time to community services offering my time to non-profit organizations, serving the communities in search and rescue missions, wandering the metro cities doing urban photography, and spending quality time at home with my family.

  I am most skilled in: <mark>network security</mark>, <mark>network switching</mark>, <mark>open-source intelligence gathering</mark>, <mark>Windows Server administration</mark>, and <mark>project management</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Consolidated Precision Products
        link: cppcorp.com
        # link_text: boringcompany.com
        sub_title: Network Security Engineer
        caption: April 2023 - Present
        description: | # this will include new lines to allow paragraphs
            With my transition from infrastructure team to security team, I took on more security-oriented responsibilities in addition to my infrastructure duties. I have been working on implementing network security measures such as 802.1X, rolling out network monitoring solutions, implementing and managing stateless and stateful firewalls. On the infrastructure side, I have begun to take on duties of mnanaging, handling and troubleshooting our Azure resources, including vNets, on Azure Government.

              <mark>SIEM</mark>, <mark>EDR</mark>, <mark>OSINT</mark>, <mark>RADIUS</mark>, <mark>PKI</mark>, <mark>AAA</mark>, <mark>802.1X</mark>, <mark>EAP-TLS</mark>, <mark>Governance, Risk, and Compliance</mark>, <mark>Fortigate</mark>, <mark>Stateless & Stateful ACL Firewalls</mark>, <mark>NAC</mark>

      - layout: left
        title: Consolidated Precision Products
        link: cppcorp.com
        # link_text: boringcompany.com
        sub_title: System Administrator
        caption: June 2012 - April 2023
        description: | # this will include new lines to allow paragraphs
            What initially started as a two weeks temporary full-time IT technician with minimal IT background to support the early Windows XP to Windows 7 migration grew into a permanent full-time position where I found myself taking on more technical challenges and making increasingly critical decisions that would have impactful effects on the business growth, drive IT policies and procedures, and set performance gold standard for the rest of the IT to adhere to.

            During the time I grew in this role, I oversaw numerous infrastructure overhaul projects, participated in the business merging and acquisitions, developed standards and procedures, trained and managed team of four as team lead, and a primary point of contact for IT support during business emergencies. Whoever and wherever I go to assist, I also make sure the support experience I’m delivering is top-notch in making sure users feel supported and seen.

      - layout: left
        title: Virtual Machine Solutions
        link: virmach.com
        # link_text: boringcompany.com
        sub_title: Level 3 Technical Support Contractor
        caption: February 2018 - May 2018
        description: | # this will include new lines to allow paragraphs
            During my short contract supporting cloud service provider, I lend my support to address service abusers, handled Level 1-3 support cases, handled customer billings, and monitored server performance hosted at multiple datacenters across USA and Europe.

      - layout: left
        title: Redlands East Valley Highschool
        link: rev.redlandsusd.net/
        # link_text: boringcompany.com
        sub_title: PC Technician
        caption: August 2010 - June 2011
        description: | # this will include new lines to allow paragraphs
            My entry into IT began working as a Level 1 technician for my local highschool campus, providing on-site support to teachers and school classrooms. I was involved in performing end of year inventory and the imaging and deployment of computer hardware for the campus.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Crafton Hills Community COllege
        caption: 2011 - 2013
        sub_title: Student
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Hiking
      - Gaming
      - Reading
      - Outdoor Photography

      Look at this cool image  
      ![Trees](images/sedona1.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
