# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tune Katerungroch
title: Senior System Administrator
email: contact@tunek.cloud
#website: https://www.linkedin.com/in/tunek/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  naamtune
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: tunek
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Tune Katerungroch, an IT professional based in Southern California, USA. Having accumulated over 14 years of professional IT experience, I have fostered excellence in the following specialties: open-source intelligence gathering, network engineering, and systems administration. I am currently working for Consolidated Precision Products as a security analyst.

  My passion in technologies took root in a humble beginning of building home computer with my father on the floor of the living room when I was a toddler. As I grew older, I self-taught myself technical skills and concepts through hand-on experience and contents made available on the Internet. In later life, my career growth took a leap forward as I begun to professionally collaborate with peers in the industry. 

  I enjoy tackling the challenges of managing projects, hardware logistics, and technical issues that spring up, as if they are minigames and puzzles. Networking issues. Infrastructure planning, and figuring out resources are just some of the shapes and forms where challenges arise. The problem-solving skills and thought process is always a reflection of one’s neuroplasticity and the quality of the mental framework. 

  Much of my IT career have been spent supporting infrastructure within the logistics and manufacturing industry, thus I have deep understanding of the business operations and how these businesses utilize IT to grow and expand.

  Outside of my professional life, I can be found in the outdoor settings rappelling down waterfalls with my teams, and scaling steep rocky desert mountains with my friends. If I’m not outside on weekend adventures as weekend warrior, I can also be found volunteering my time to community services offering my time to non-profit organizations, serving the communities in search and rescue missions, wandering the metro cities doing urban photography, and spending quality time at home with my family.

  I am most skilled in: <mark>network security</mark>, <mark>network switching</mark>, <mark>open-source intelligence gathering</mark>, <mark>Windows Server administration</mark>, and <mark>project management</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Consolidated Precision Products
        link: cppcorp.com
        # link_text: boringcompany.com
        sub_title: Network Security Engineer
        caption: April 2023 - Present
        description: | # this will include new lines to allow paragraphs
            ## Summary
            With my transition from infrastructure team to security team, I took on more security-oriented responsibilities in addition to my infrastructure duties. I have been working on implementing network security measures such as 802.1X, rolling out network monitoring solutions, implementing and managing stateless and stateful firewalls. On the infrastructure side, I have begun to take on duties of mnanaging, handling and troubleshooting our Azure resources, including vNets, on Azure Government.  
            ## Experience
            * Led the implementation of 802.1X on wired network and wireless network to move toward passwordless authentication, reduce attack vectors, address technical shortcomings with previous authentication method, reduce network overheard, and minimize password-related tickets.
            * Led the implementation of AAA on network switches across the entire corporate infrastructure to enable security logging, create accountability, to grant RBAC to local IT teams, and reduce IT overhead.
            * Deployed and configured Solarwinds NPM/NCM/NTA modules to create tailored network monitoring of the internal network infrastructure to improve response time to network outage and degraded system performance.
            * Configured, maintained, and troubleshoot stateless and stateful firewalls (ACL/Pfsense), and receive/fulfill blacklist/whitelist application/port requests from IT team members for 6+ facilities in Southern California region.
            * Improve network backbone throughput, capacity, and uptime through 10G fiber uplink overhaul, implementation of VSF, RSTP, DHCP snooping, and LACP.
            * Through collaborative efforts with automation team, planned, configured, and deployed SCADA network for the rollout of PLCs, industrial IoTs and data collectors for 4+ Californian facilities. 
            * Worked closely with security team, infrastructure team, and stakeholders to address critical/high-priority vulnerabilities found through Nessus/Rapid7.
            * Collaborated with security team and upper management to author/coauthor company-wide security policies and procedures to satisfy regulations and compliance. 

            **Technical Skills:** <mark>Network switching</mark> <mark>OSINT</mark> <mark>GRC</mark> <mark>SIEM monitoring</mark> <mark>vulnerability assessment</mark> <mark>cloud network engineering</mark> <mark>network security</mark> <mark>incident responder</mark>  
            **Technologies:** <mark>Azure</mark> <mark>Sentinel1</mark> <mark>Carbon Black</mark> <mark>Trendmicro</mark> <mark>Nessus</mark> <mark>Nmap</mark> <mark>OpenSSL</mark> <mark>PKI</mark> <mark>Pfsense</mark> <mark>Fortigate</mark> <mark>ACL</mark> <mark>VSF</mark> <mark>RSTP</mark> <mark>MSTP</mark> <mark>LACP</mark> <mark>DHCP snooping</mark> <mark>port security</mark> <mark>802.1X</mark> <mark>AAA</mark> <mark>Solarwinds</mark> <mark>SCADA</mark> <mark>PLC</mark> <mark>Ignition</mark> <mark>Git</mark>  
            ---
      - layout: left
        title: Consolidated Precision Products
        link: cppcorp.com
        # link_text: boringcompany.com
        sub_title: System Administrator
        caption: June 2012 - April 2023
        description: | # this will include new lines to allow paragraphs
            ## Summary
            What initially started as a two weeks temporary full-time IT technician with minimal IT background to support the early Windows XP to Windows 7 migration grew into a permanent full-time position where I found myself taking on more technical challenges and making increasingly critical decisions that would have impactful effects on the business growth, drive IT policies and procedures, and set performance gold standard for the rest of the IT to adhere to.

            During the time I grew in this role, I oversaw numerous infrastructure overhaul projects, participated in the business merging and acquisitions, developed standards and procedures, trained and managed team of four as team lead, and a primary point of contact for IT support during business emergencies. Whoever and wherever I go to assist, I also make sure the support experience I’m delivering is top-notch in making sure users feel supported and seen.  

            ## Experience
            * Led and deployed lite-touch imaging service using Powershell, WDS, and MDT to California region to automate hardware imaging process down to 10 minutes lead-time at minimal cost.
            * Led and managed $150k-$300k network and servers infrastructure overhaul projects at each of the 6+ Californian fand Mexican acilities through planning, budgeting, configuring, installation, and migration.
            * Rescued business operations from $14M+ loss in productivity triggered by a singular computer security lockout on legacy SCADA hardware due to operator error.
            * Improved quality of wireless coverage and refreshed wireless network infrastructure at 6+ locations through heatmapping, planning, budgeting, and deployment of Meraki wireless access points across 6+ facilities in California, Minnesota, Ohio, and Ensenada, Mexico.
            * Deployed and administered 3-2-1 policies and Veeam backup solution at 6+ sites with automated workstation agent deployment, and was responsible for monitoring alerts and testing backup integrity on a weekly and monthly basis.
            * Provided on-site and remote Level 1-3 support across USA and Mexico, serving 500+ users and 500+ endpoints at 16+ facilities.
            * Deployed a centralized documentation system to house technical notes and source of truth, reducing siloed tribal knowledge, establish information integrity and availability, and to foster collaboration between regional IT teams. 
            * Worked with local facility management team to gather evidence, procedures, and policies to provide to federal government agencies for audits.
            * Developed custom Powershell scripts to automate repetitive mundane tasks to free up time and resources to focus on more impactful tasks and projects.
            * Manage/Configure/Troubleshoot Microsoft O365/Entra/Azure technical issues.

            **Technical Skills:** <mark>Leadership</mark> <mark>Powershell</mark> <mark>SQL</mark> <mark>Python</mark> <mark>C++</mark> <mark>PHP</mark> <mark>TCP/IP</mark> <mark>hardware reverse engineering</mark> <mark>technical writing</mark> <mark>network architect</mark> <mark>database administration</mark>  
            **Technologies:** <mark>Windows Server 2012/2016/2019/2022</mark> <mark>Windows 2000/XP/7/10/11</mark> <mark>Linux</mark> <mark>WDS</mark> <mark>MDT</mark> <mark>Powershell</mark> <mark>Visio</mark> <mark>Office 365</mark> <mark>Entra</mark> <mark>Confluence</mark> <mark>Wiki.js</mark> <mark>Windbg</mark> <mark>Ollydbg</mark> <mark>Sysinternals</mark> <mark>VMWare ESX</mark> <mark>MySQL</mark> <mark>MSSQL</mark> <mark>Veeam</mark> <mark>Grapfana</mark> <mark>Kaftka</mark>  
            ---
      - layout: left
        title: Virtual Machine Solutions
        link: virmach.com
        # link_text: boringcompany.com
        sub_title: Level 3 Technical Support Contractor
        caption: February 2018 - May 2018
        description: | # this will include new lines to allow paragraphs
            ## Summary
            During my short contract supporting cloud service provider, I lend my support to address service abusers, handled Level 1-3 support cases, handled customer billings, and monitored server performance hosted at multiple datacenters across USA and Europe.
            ## Experience
            * Handled 20+ abuse reports on daily, such as verifying the legitimacy of incoming abuse reports, confirming reports, closing down accounts, shutting down malicious services, and warning customers, depending on severity of abuse and violation.
            * Handled abuse reports submitted by government agencies such as FBI.
            * Monitored and stablized server performance using provided tools such as Nixstats, iostats, sar, top, etc.
            * Combed through customers to look for abusive uses such as crypto-mining and hosting malware.

            **Technical Skills:** <mark>digital forensic investigation</mark> <mark>customer support</mark> <mark>client billings</mark> <mark>web hosting</mark>  
            **Technologies:** <mark>SolusVM</mark> <mark>cPanel</mark> <mark>WHM</mark> <mark>VPS</mark> <mark>Managed Colocations</mark> <mark>Nixstats</mark> <mark>iostats</mark> <mark>sar</mark> <mark>top</mark>  
            ---
      - layout: left
        title: Redlands East Valley Highschool
        link: rev.redlandsusd.net/
        # link_text: boringcompany.com
        sub_title: PC Technician
        caption: August 2010 - June 2011
        description: | # this will include new lines to allow paragraphs
            ## Summary
            My entry into IT began working as a Level 1 technician for my local highschool campus, providing on-site support to teachers and school classrooms. I was involved in performing end of year inventory and the imaging and deployment of computer hardware for the campus.
            ## Experience
            * Imaged 50+ school computers and verified the computers are working as intended.
            * Assisted with level 1 helpdesk issues. 
            * Managed the school campus website.

            **Technical Skills:** <mark>VBS</mark> <mark>Batch</mark>  
            **Technologies:** <mark>Symantec Ghost Imaging</mark> <mark>Windows XP</mark>

  - title: Certifications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - Cisco Certified Networking Associate (CCNA)
      - CompTIA Security+
      - CompTIA Network+
      - CompTIA A+
      - Microsoft Azure Security, Compliance, and Identity Fundamentals (SC-900)
      - Microsoft Azure Network Fundamentals (AZ-900)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Hiking
      - Gaming
      - Reading
      - Outdoor Photography

      Look at this cool image  
      ![Trees](images/sedona1.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
